{"name": "测试用例描述：错误的账号登录失败", "status": "passed", "description": "测试描述：错误的账号登录失败", "steps": [{"name": "输入错误的账号", "status": "passed", "attachments": [{"name": "错误的账号", "source": "c9f08c34-e88a-4dc3-bc4a-368216f777fa-attachment.attach"}], "start": 1651990809442, "stop": 1651990809442}], "attachments": [{"name": "截图", "source": "f1e81ef7-b480-49a4-84d0-2dd6e9017087-attachment.png", "type": "image/png"}], "start": 1651990809441, "stop": 1651990812206, "uuid": "5943cb2e-b6ef-4a56-a405-b0e2628f324a", "historyId": "dac4ae518a5085ee93a0eeeab00b80d4", "testCaseId": "60e0d8659bd2e52aa6ebe8c64f9be9b0", "fullName": "test_login.Test#test_21", "labels": [{"name": "story", "value": "登录"}, {"name": "severity", "value": "critical"}, {"name": "feature", "value": "登录模块"}, {"name": "epic", "value": "xxx测试"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "11376-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}